# Changes here will be overwritten by Copier
_commit: v0.3.0b1
_src_path: gh:deeplex/copier-cpp
email: henrik@gassmann.onl
full_name: Henrik Steffen Gaßmann
header_config: true
header_only: true
namespace: cncr
project_name: concrete
project_slug: concrete
workaround_header: true
year: 2022-2023
